services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: Asia/Kolkata
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres-data:
